me: Update web servers
  hosts: all
  become: yes
  vars:
    http_port: 80

  tasks:
  - name: copy httpd conf
    template:
      src: httpd.j2
      dest: /etc/httpd/conf/httpd.conf
    notify:
    - restart httpd

  handlers:
  - name: restart httpd
    service:
      name: httpd
      state: restarted

...
